version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gorm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: gorm_demo
      MYSQL_USER: gorm
      MYSQL_PASSWORD: gorm123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - gorm-network

volumes:
  mysql_data:
    driver: local

networks:
  gorm-network:
    driver: bridge