swagger: '2.0'
info:
  title: 文件上传系统 API
  description: 基于领域驱动设计的文件上传系统API，支持单文件上传、多文件上传、文件夹上传及大文件分片上传
  version: '1.0'
  contact:
    name: 开发团队
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
host: localhost:8080
basePath: /
schemes:
- http
consumes:
- application/json
- multipart/form-data
produces:
- application/json
tags:
- name: 上传
  description: 文件上传相关接口
