version: "3.9"

services:
  backend:
    container_name: miniblog
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    # 镜像名
    image: mysql
    # 容器名(以后的控制都通过这个)
    container_name: miniblog-db
    # 重启策略
    restart: unless-stopped
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: 123456
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: forest_config
      # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
      MYSQL_USER: Forest
      # 用户密码
      MYSQL_PASSWORD: Forest
      # 映射端口
    ports:
      - 11006:3306
    volumes:
      # 数据挂载
      #- /root/mysql/data/:/var/lib/mysql/
      # 配置挂载
      #- /root/mysql/conf/:/etc/mysql/conf.d/
      # 初始化目录挂载，注意此处我只跑了这个挂载，只是为了说明其他配置不应该数据初始化
      - ./.dbdata/:/docker-entrypoint-initdb.d/
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
