services:
  db:
    image: mysql:8.0
    container_name: gormgen-mysql
    restart: always
    environment:
      MYSQL_DATABASE: gormgen
      MYSQL_USER: gorm
      MYSQL_PASSWORD: gorm123456
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - gorm-network

volumes:
  mysql_data:
    driver: local

networks:
  gorm-network:
    driver: bridge